name: DEV - Build & deploy App
run-name: Build & deploy ASP.NET Core app to az app ${{ github.sha }}

permissions: {}

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    types:
      - opened         # When a PR is created
      - synchronize    # When commits are pushed to the PR branch
      - reopened       # When a closed PR is reopened
    paths:
      - '.github/workflows/dev-app-ci-cd.yaml'
      - 'WebAppNetCore6/**'
      - '!**.md'


env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'                        # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                               # set this to the .NET Core version to use. LibMan requires .NET 8.0.x to inject libraries

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set up dependency caching for faster builds
      uses: actions/checkout@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    environment: dev
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_REGION_1 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}