name: STG - Build & deploy App
run-name: Build & deploy ASP.NET Core app to az app

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    paths:
      - '!**.md'
      - '.github/workflows/stg-app-ci-cd.yaml'
      - 'WebAppNetCore6/**'

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'                        # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                               # set this to the .NET Core version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set up dependency caching for faster builds
      uses: actions/checkout@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy-region-1:
    runs-on: ubuntu-latest
    environment: stg
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_REGION_1 }}
          slot-name: ${{ vars.AZURE_WEBAPP_SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_REGION_1 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-region-2:
    runs-on: ubuntu-latest
    environment: stg
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_REGION_2 }}
          slot-name: ${{ vars.AZURE_WEBAPP_SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_REGION_2 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}